# Jekyll configuration
markdown: kramdown
highlighter: rouge
paginate: 15 # it will paginate after this number
language: 'en-uk'

baseurl: https://madcode-git.github.io/
production_url: https://madcode-git.github.io/

# Website info
title: RayhanBD
description: The professional publishing platform
cover: assets/images/blog-cover.jpg
logo: assets/images/blog-icon.png
logo_dark: assets/images/favicon.png
favicon: assets/images/favicon.png
CNAME: 

# Social info
navigation: True
subscribers: True
twitter: tryghost
facebook: ghost
disqus: False
disqus_shortname: jekyller
google_analytics: 

# Permalinks
permalink: /:title
permalink: /author/:author
permalink: /tag/:tag

# gems and other configs
plugins_dir: [_plugins]
plugins: [jekyll-paginate, jekyll-feed]

feed:
  path: feed.xml

exclude:
  - assets/css
  - node_modules
  - vendor
  - .travis.yml
  - Gemfile
  - Gemfile.lock
  - GHOST.txt
  - gulpfile.js
  - LICENSE
  - package.json
  - Rakefile
  - README.md
  - script.py
  - changelog.md
  - "*.Rmd"
  - .git*